name: beta

on:
  push:
    branches: [beta]

jobs:
  notify-api:
    name: Notificar a control-api (beta) para refrescar recursos
    runs-on: ubuntu-latest
    steps:
      - name: Update resources (beta)
        env:
          # TODO: confirmar la URL de control-api de BETA
          API_URL: "https://control-api-beta.e-middleware.ar/notify/update-resources"
          APP_KEY: ${{ secrets.NOTIFY_APP_KEY }}
        run: |
          curl -X POST "$API_URL" \
            -H 'accept: application/json' \
            -H "app_key: $APP_KEY" \
            -d ''
