name: Notify external system

on:
  push:
    branches:
      - main

jobs:
  notify-api:
    runs-on: ubuntu-latest

    steps:
      - name: Update dev environment
        env:
          API_URL: "https://control-api.e-middleware.dev/notify/update-resources"
          APP_KEY: ${{ secrets.NOTIFY_APP_KEY }}
        run: |
          curl -X 'POST' \
            "$API_URL" \
            -H 'accept: application/json' \
            -H "app_key: $APP_KEY" \
            -d ''

      - name: Update prod environment
        env:
          API_URL: "https://jmc-control-api.e-middleware.ar/notify/update-resources"
          APP_KEY: ${{ secrets.NOTIFY_APP_KEY }}
        run: |
          curl -X 'POST' \
            "$API_URL" \
            -H 'accept: application/json' \
            -H "app_key: $APP_KEY" \
            -d ''
